server:
  port: ${GATEWAY_PORT:8082}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.39.129:30180/realms/toolrent
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.39.129:30180/realms/toolrent/protocol/openid-connect/certs
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: m1
          uri: lb://m1
          predicates:
            - Path=/m1/**
        - id: m2
          uri: lb://m2
          predicates:
            - Path=/m2/**
        - id: m3
          uri: lb://m3
          predicates:
            - Path=/m3/**
        - id: m4
          uri: lb://m4
          predicates:
            - Path=/m4/**
        - id: m5
          uri: lb://m5
          predicates:
            - Path=/m5/**
        - id: m7
          uri: lb://m7
          predicates:
            - Path=/m7/**            


