server:
  port: ${GATEWAY_PORT:8082}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.192.168.39.111.nip.io/realms/toolrent
          jwk-set-uri: http://keycloak:8080/realms/toolrent/protocol/openid-connect/certs
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
            exposed-headers:
              - Authorization
      routes:
        - id: m1
          uri: lb://m1
          predicates:
            - Path=/m1/**
        - id: m2
          uri: lb://m2
          predicates:
            - Path=/m2/**
          filters:
            - RewritePath=/m3/(?<segment>.*), /${segment}
        - id: m3
          uri: lb://m3
          predicates:
            - Path=/m3/**
          filters:
            - RewritePath=/m3/(?<segment>.*), /${segment}
        - id: m4
          uri: lb://m4
          predicates:
            - Path=/m4/**
          filters:
            - RewritePath=/m3/(?<segment>.*), /${segment}
        - id: m5
          uri: lb://m5
          predicates:
            - Path=/m5/**
          filters:
            - RewritePath=/m3/(?<segment>.*), /${segment}
        - id: m7
          uri: lb://m7
          predicates:
            - Path=/m7/**
          filters:
            - RewritePath=/m3/(?<segment>.*), /${segment}
















