server:
  port: ${GATEWAY_PORT:8082}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: m1
          uri: lb://m1-headless
          predicates:
            - Path=/m1/**
        - id: m2
          uri: lb://m2-headless
          predicates:
            - Path=/m2/**
        - id: m3
          uri: lb://m3
          predicates:
            - Path=/m3/**
        - id: m4
          uri: lb://m4-headless
          predicates:
            - Path=/m4/**
        - id: m5
          uri: lb://m5-headless
          predicates:
            - Path=/m5/**
