server:
  port: 8080
spring:
  cloud:
    gateway:

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      routes:
        - id: moves
          uri: http://ms-moves:8083
          predicates:
            - Path=/api/v1/moves/**

        - id: income
          uri: http://ms-income:8082
          predicates:
            - Path=/api/v1/income/**

        - id: expenses
          uri: http://ms-expenses:8081
          predicates:
            - Path=/api/v1/expenses/**

        - id: m2
          uri: lb://m2
          predicates:
            - Path=/m2/**
          filters:
            - RewritePath=/m3/(?<segment>.*), /${segment}
        - id: m3
          uri: lb://m3
          predicates:
            - Path=/m3/**
          filters:
            - RewritePath=/m3/(?<segment>.*), /${segment}
        - id: m4
          uri: lb://m4
          predicates:
            - Path=/m4/**
          filters:
            - RewritePath=/m3/(?<segment>.*), /${segment}
        - id: m5
          uri: lb://m5
          predicates:
            - Path=/m5/**
          filters:
            - RewritePath=/m3/(?<segment>.*), /${segment}
        - id: m7
          uri: lb://m7
          predicates:
            - Path=/m7/**
          filters:
            - RewritePath=/m3/(?<segment>.*), /${segment}


















