server:
  port: ${GATEWAY_PORT:8082}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA_HOST:eureka-service}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: m1
          uri: lb://m1
          predicates:
            - Path=/m1/**

        - id: m2
          uri: lb://m2
          predicates:
            - Path=/m2/**

        - id: m3
          uri: lb://m3
          predicates:
            - Path=/m3/**

        - id: m4
          uri: lb://m4
          predicates:
            - Path=/m4/**

        - id: m5
          uri: lb://m5
          predicates:
            - Path=/m5/**