server:
  port: ${SERVER_PORT}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak.192.168.39.129.nip.io/realms/toolrent/protocol/openid-connect/certs
  application:
    name: m1
eureka:
  instance:
    preferIPAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/


