server:
  port: ${SERVER_PORT}
spring:
  application:
    name: m5
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 465
    username: mauryr2001@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          mechanisms: XOAUTH2
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    preferIPAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
