server:
  port: ${SERVER_PORT}
spring:
  application:
    name: m7
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak.192.168.39.129.nip.io/realms/toolrent/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    preferIPAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
